version: '3.7'
services:

  mysql:
    container_name: mysql
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: quarkus
      MYSQL_USER: quarkus
      MYSQL_PASSWORD: quarkus
      MYSQL_DATABASE: quarkus
      TZ: America/Sao_Paulo

  localstack:
    container_name: localstack
    image: localstack/localstack:0.11.2
    volumes:
      - ./src/main/docker/create_sqs_queues.sh:/docker-entrypoint-initaws.d/create_sqs_queues.sh
    ports:
      - "4566:4566"
    environment:
      DEFAULT_REGION: sa-east-1
      FORCE_NONINTERACTIVE: 1
      USE_SSL: 0
      SERVICES: sqs

  application:
    container_name: application
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.native
      #dockerfile: src/main/docker/Dockerfile.jvm
    ports:
      - "8080:8080"